### ISSUE TITLE
Timeout doesn't work with node-fetch

### ISSUE THREAD

**Issue by RodolfoGS** [TooTallNate/proxy-agents#53]
Hi, I have this simple code and the timeout doesn't work with `node-fetch` library.
I'm trying to use this proxy `192.40.242.55:53281` (doesn't work, I know) and the timeout doesn't work.

```
var fetch = require('node-fetch');
var HttpsProxyAgent = require('https-proxy-agent');

var proxy = 'http://192.40.242.55:53281';
var options = {
    timeout: 5000,
    agent: new HttpsProxyAgent(proxy),
};

var time = +new Date();
fetch('http://httpbin.org/ip', options)
	.then(res => res.json())
	.then(json => {
		console.log(json);
		console.log('Time: ' + (+new Date() - time));
	})
	.catch(err => {
		console.error(err);
		console.log('Time: ' + (+new Date() - time));
	});
```

My response using the debug flag: `DEBUG=* node app.js`:
```
  https-proxy-agent creating new HttpsProxyAgent instance: Url { protocol: 'http:', slashes: true, auth: null, host: '192.40.242.55:53281', port: '53281', hostname: '192.40.242.55', hash: null, search: null, query: null, pathname: '/', path: '/', href: 'http://192.40.242.55:53281/' } +0ms
{ FetchError: request to http://httpbin.org/ip failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/rodolfo/Downloads/proxies/node_modules/node-fetch/lib/index.js:1393:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at onerror (/Users/rodolfo/Downloads/proxies/node_modules/agent-base/index.js:101:9)
    at callbackError (/Users/rodolfo/Downloads/proxies/node_modules/agent-base/index.js:123:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'request to http://httpbin.org/ip failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Time: 48375
```

The request took 48375 milliseconds instead of 5000 of my timeout.
I tested the above code with the `http-proxy-agent` library and works perfectly.

Any idea that what happened?

**Comment by astur** [comment]
It's not only with node-fetch.

For example, this code:

```js
const request = require('got');
const HttpsProxyAgent = require('https-proxy-agent');
const agent = new HttpsProxyAgent('http://very.slow.proxy');

request('https://example.com', {
    agent,
    timeout: 1000,
    retry: 0,
})
    .then(r => console.log(r))
    .catch(e => console.log(e));

```

It will not stop after error, cause socket will not be closed at same moment.

Using `wtfnode` you can see something like this:

```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Sockets:
  - 192.168.1.51:53797 -> undefined:undefined
    - Listeners:
Unable to determine callsite for "Function". Did you require `wtfnode` at the top of your entry point?
      - connect: (anonymous) @ unknown:0
Unable to determine callsite for "connect". Did you require `wtfnode` at the top of your entry point?
      - connect: connect @ unknown:0
```
